### ISSUE TITLE
Mapping quality as adjustable parameter

### ISSUE THREAD

**Issue by mzwaig** [sgreer77/gemtools#1]
Hello,

I'm trying to use the output from get_shared_bcs for my analysis, however, it picks up the barcodes from a lot of low quality alignments.
Is there anyway to make mapping quality an adjustable parameter?

Thank you,
Melissa

**Comment by sgreer77** [comment]
Hi Melissa, 

Apologies -- somehow I missed this issue. I have just made this change. You can now use a '-q' flag to set the quality, for example '-q 30' for reads with mapping quality >30.

Thanks for pointing out this issue.
